# i wanna dev a internal motivation learning , def with RL, it reward itself . make an nn, for example , nn wanna do an operation which is output number 5, he have an operator, like his hands, but hands function is solid, what his mind can do is control 3 neurons , so he input 5 (what he want) and then became the 3 neurons output, and the 3 neurons will drive to output , but this part parameter cannot change. help me make code in pytorch , make he learn use tool output interger 0to 9  as he wish























